<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Admin' => 'Администратор',
  'Captcha' => 'Код',
  'Confirm password' => 'Подтвердите пароль',
  'Create User' => 'Создать пользователя',
  'Incorrect username or password.' => 'Не верный логин или пароль',
  'Login' => 'Войти',
  'Logout' => 'Выйти',
  'Manage Users' => 'Управление пользователями',
  'Password' => 'Пароль',
  'Password:' => 'Пароль:',
  'Please fill out the following form with your login credentials:' => 'Пожалуйста, для входа заполните форму Вашими данными',
  'Registration date' => 'Дата регистрации',
  'Remember me next time' => 'Запомнить меня',
  'Role' => 'Роль',
  'Status' => 'Статус',
  'Update User' => 'Редактировать пользователя',
  'User' => 'Пользователь',
  'Username' => 'Логин',
  'Username:' => 'Логин:',
  'Address' => 'Адрес',
  'Phone' => 'Телефон',
  'Name' => 'Имя',
  'Add role' => 'Добавить роль',
  'Manage users roles' => 'Управление ролями пользователей',
);
